## NumPy indexing and selection

In [42]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

We can 'broadcast'(assign) a value to multiple values simultaneously.

In [8]:
# arr[1:4:1] = 100
arr[0:6] = 100

In [9]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [10]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [11]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Slicing and assigning

In [12]:
slice_arr = arr[:5]
slice_arr

array([0, 1, 2, 3, 4])

In [13]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100])

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Here , <code>slice_arr</code> holds a reference to the original array.</b>
instead of having another copy.

In [15]:
arr_copy = arr.copy()

In [16]:
print(arr_copy,arr,sep = '\n')

[100 100 100 100 100   5   6   7   8   9  10]
[100 100 100 100 100   5   6   7   8   9  10]


In [17]:
arr_copy[:5] = 0

In [18]:
print(arr_copy,arr,sep='\n')

[ 0  0  0  0  0  5  6  7  8  9 10]
[100 100 100 100 100   5   6   7   8   9  10]


### Indexing a 2-D array

In [43]:
arr_2d =   np.array([[5,10,15], [20,25,30], [35,40,45]])

In [44]:
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [21]:
arr_2d[0][0]

5

In [22]:
arr_2d[0]

array([ 5, 10, 15])

In [23]:
print(arr_2d[2][1])
print(arr_2d[2,1])

40
40


In [49]:
# TO GRAB PARTS/SUBMATRICES
#arr_2d[:2,1:] # GRAB UPTO(excluding) 2nd ROW and FROM 1st column and
              # ONWARDS              
print(arr_2d[:1,1:])   

[[10 15]]


### Conditional selections

In [25]:
arr = np.arange(1,11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 5
# A FULL BOOLEAN ARRAY DEPENDING ON THE RESULT 
# WHEN EACH ELEMENT OF ARRAY IS 'AUTOMATICALLY' ITERATED 
# OVER THE COMPARISON 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [28]:
# WE CAN ASSIGN THE BOLLEAN ARRAY
boolean = arr > 5
boolean

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
arr[ boolean]

array([ 6,  7,  8,  9, 10])

This iterates every element of arr and checks whether boolean is true<br> 
or not

In [30]:
# OR SIMPLY
print(arr[:])

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
print(arr[arr > 5])

[ 6  7  8  9 10]


In [32]:
print(arr[arr<3])

[1 2]


In [52]:
arr_2d = np.arange(0,50).reshape(5,10)

In [53]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
arr_2d[1:4,4:7]

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [65]:
print(arr_2d[1:2,5::-1])

[[15 14 13 12 11 10]]
