### Introduction

Linear algebra library for Python.<br>
Many libraries rely on NumPy as one of the main building blocks.<br>
Fast , due to bindings with C libraries.


NumPy Arrays:

<pre>
NumPy arrays - 
                1-D - Vectors
                2-D - Matrix
</pre>               

In [2]:
my_list = [1,2,3]

In [5]:
import numpy as np

In [4]:
type(np.array(my_list))

numpy.ndarray

In [5]:
A = np.array(my_list)

In [6]:
A

array([1, 2, 3])

In [7]:
print(A)

[1 2 3]


In [8]:
my_mat = [ [1,2,3] , [4,5,6] , [7,8,9] ]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(np.array(my_mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### NumPy's built in generation methods to create : 

arange(start,stop,step) - Works similar to range()

In [4]:
np.arange(0,10,1)     # SIMILAR TO RANGE FUNCTION
#        START-STOP-STEP
#              (not included) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

<code>zeros(size)</code> - to create an array consisting of zeros (default-float)<br>
<code>ones(size) </code> - to create an array consisting of ones (default-float)<br>
size can be either passed as single int : for 1-D<br>
or in form of <code>tuple-()</code> with comma-separated values for 2-D.<br>

In [13]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [16]:
A = np.array(list(map(int,np.zeros(5))))
print(A)

[0 0 0 0 0]


In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [51]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
B = np.array(list(map(int,np.ones(5))))
print(B)

[1 1 1 1 1]


In [20]:
C = np.zeros((3,5))
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
D = np.array(list(map(int,C)))
print(D)

TypeError: only size-1 arrays can be converted to Python scalars

<code>linspace</code> - returns evenly distributed integers over a specified interval (inclusive)<br>
It returns a <b>one</b>-dimensional array

In [34]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

<code>eye</code>- returns an identity matrix of order specified as parameter.<br>
It returns a <b>two</b>-dimensional array.

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Arrays of random numbers -

  <code>np.random.rand</code> - Uniform distribution.

In [25]:
np.random.rand(5)  #CREATE AN ARRAY AND FILL WITH RANDOM FROM 0-1
                   # UNIFORMLY DISTRIBUTED

array([0.2922857 , 0.99949986, 0.78651358, 0.66603442, 0.95152199])

In [26]:
np.random.rand(5,5) # DOESN'T REQUIRE TUPLE NOTATION

array([[0.01410338, 0.15451594, 0.89273149, 0.01040152, 0.10997686],
       [0.97906403, 0.69295739, 0.36811319, 0.66334208, 0.91508516],
       [0.42900439, 0.22700347, 0.16379555, 0.76228116, 0.97018554],
       [0.16726387, 0.41217758, 0.46122744, 0.22975678, 0.16298673],
       [0.63262392, 0.57444182, 0.60805448, 0.0911457 , 0.65321117]])

<code>np.random.randn</code>-Standard normal distribution(around zero)

In [27]:
np.random.randn(5)

array([2.00260993, 1.46793883, 0.05862918, 0.15875518, 0.70043619])

In [30]:
np.random.randn(4,4) # DOESN'T REQUIRE TUPLE NOTATION

array([[-0.36697215,  1.10375893,  0.22351649,  1.1758652 ],
       [ 1.29596949, -0.85226788,  3.55502327, -2.14471864],
       [-1.69108991, -1.27258257, -0.11516086, -0.63911002],
       [ 0.90738837,  1.00113576,  2.7158267 , -1.13311952]])

<code>np.random.randint</code>-Random integers from<br> 
start(inclusive) to end(exclusive).

In [9]:
np.random.randint(1,100)

93

In [39]:
np.random.randint(1,100,10)

array([29, 62, 57, 38, 33, 82, 21,  9, 42, 44])

### Useful attributes of array

In [40]:
A = np.arange(25)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
randarr = np.random.randint(0,50,10)
randarr

array([38, 14, 20, 45, 14, 23,  5,  0, 42, 26])

In [43]:
A.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
A  # NO CHANGE IN ORIGINAL

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
print("Max:",A.max(),"at index:",A.argmax())
print("Max:",randarr.max(),"at index:",randarr.argmax())


Max: 24 at index: 24
Max: 45 at index: 3


In [45]:
print("Min:",A.min(),"at index:",A.argmin())
print("Min:",randarr.min(),"at index:",randarr.argmin())

Min: 0 at index: 0
Min: 0 at index: 7


If we have multiple entries of max/min element , argmax()/argmin()<br>
will return the first occurence . 

In [46]:
A.shape

(25,)

In [47]:
B = A.reshape(5,5)

In [48]:
B.shape

(5, 5)

In [49]:
A.dtype

dtype('int32')